services:

  db:
    image: mysql
    restart: always
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
